# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install R
      - name: Install-R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.4' # The R version to load (if necessary) and use.
      # Run Script
      - run: Rscript -e 'print("Hello World")'
